name: Build Docker image

# Controls when the workflow will run
on:
  workflow_dispatch: {}
  push:
    branches:
    - 'main'

env:
  DOCKER_IMAGE_NAME: mosquitto
  DOCKER_BUILD_DIR: docker

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    name: Build docker image and push to GCR
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-,format=short

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define build arguments
        shell: bash
        run: |
          TIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          META_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          HASH=$(git describe --all --long --dirty --abbrev=10 --tags --always)
          REPOSITORY="git@github.com:${GITHUB_REPOSITORY}.git"
          source VERSIONS
          [[ -z "$META_VERSION" ]] || [[ "$META_VERSION" == sha-* ]] && VERSION="$META_VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TIME=${TIME}" >> $GITHUB_ENV
          echo "HASH=${HASH}" >> $GITHUB_ENV
          echo "REPOSITORY=${REPOSITORY}" >> $GITHUB_ENV

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_BUILD_DIR }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            TIME=${{ env.TIME }}
            HASH=${{ env.HASH }}